version: '3.4'

services:
  app:
    container_name: cachet_app
    build: .
    environment:
      - APP_ENV=${APP_ENV}
      - APP_NAME=${APP_NAME}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - APP_TIMEZONE=UTC
      - DB_DRIVER=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - default

  nginx:
    image: nginx:1.19.4-alpine
    container_name: cachet_nginx
    depends_on:
      - app
    tty: true
    ports:
      - "7000:80"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default

networks:
  defaults:
